---
- name: Launch proxy container
  docker_container:
    name: httpd
    image: "{{ dockerhub_username }}/tp-devops-httpd:latest"
    state: started
    restart_policy: always
    networks:
      - name: my_network
    ports:
      - "80:80"
