name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml

      - name: SonarCloud Scan
        working-directory: simple-api
        run: mvn verify sonar:sonar -Dsonar.projectKey=mehdisaadiiii_TP2-DevOPs -Dsonar.organization=mehdisaadiiii92 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set short SHA tag
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push simple-api image
        uses: docker/build-push-action@v6
        with:
          context: simple-api
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ env.SHORT_SHA }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: database
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ env.SHORT_SHA }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: http-server
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ env.SHORT_SHA }}

  deploy-ansible:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ansible repo
        uses: actions/checkout@v4
        with:
          repository: mehdi-saadi-engineer/TP3-DevOps
          path: ansible
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
  
      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mehdi.saadi.takima.cloud >> ~/.ssh/known_hosts
  
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --extra-vars "ansible_python_interpreter=/usr/bin/python3"

